In [1]:
import numpy as np
from random import random
from sklearn.model_selection import train_test_split

import tensorflow as tf

In [ ]:
#Task------------

#build model

#compile model

#train model

#evaluate model

#make predictions

In [2]:
#split training and test

def generate_dataset(num_samples, test_size):
    #dummy dataset
    x = np.array([[random() / 2 for _ in range(2)] for _ in range (num_samples)]) #array([[0.1, 0.2], [0.3, 0.4]])
    y = np.array([[i[0] + i[1]] for i in x])                         #array([[0.6], [0.7]])

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=test_size) # pass inputs and outputs
    return x_train, x_test, y_train, y_test

In [3]:
x_train, x_test, y_train, y_test = generate_dataset(5000, 0.3)

print("x_test: \n {}".format(x_test))
print("y_test: \n {}".format(y_test))

x_test: 
 [[0.08389716 0.10863255]
 [0.26060081 0.34060955]
 [0.25789456 0.09459522]
 ...
 [0.28104566 0.082955  ]
 [0.26386772 0.35762743]
 [0.18617618 0.36905665]]
y_test: 
 [[0.19252971]
 [0.60121036]
 [0.35248978]
 ...
 [0.36400066]
 [0.62149516]
 [0.55523283]]


In [4]:
x_train

array([[0.29562642, 0.08660362],
       [0.47475097, 0.00464517],
       [0.48325011, 0.17660517],
       ...,
       [0.00722866, 0.34700338],
       [0.18246672, 0.32135149],
       [0.23365304, 0.30332441]])

In [7]:

#building the model

#2 neurons input - 5 neurons 1 hidden - 1 neuron output
model = tf.keras.Sequential([
    tf.keras.layers.Dense(5, input_dim = 2, activation="sigmoid"), #input-hidden
    tf.keras.layers.Dense(1, activation="sigmoid")                #output
]) #a sequential (L-R model)

In [8]:

#compile
optimiser = tf.keras.optimizers.SGD(learning_rate=0.1)          #stochastic gradient descent
model.compile(optimizer=optimiser, loss="MSE")


#train
model.fit(x_train, y_train, epochs=100)

Train on 3500 samples
Epoch 1/100
3500/3500 [==============================] - 1s 181us/sample - loss: 0.0536
Epoch 2/100
3500/3500 [==============================] - 0s 113us/sample - loss: 0.0437
Epoch 3/100
3500/3500 [==============================] - 0s 112us/sample - loss: 0.0434
Epoch 4/100
3500/3500 [==============================] - 0s 109us/sample - loss: 0.0432
Epoch 5/100
3500/3500 [==============================] - 1s 189us/sample - loss: 0.0430
Epoch 6/100
3500/3500 [==============================] - 0s 97us/sample - loss: 0.0428
Epoch 7/100
3500/3500 [==============================] - 0s 111us/sample - loss: 0.0426
Epoch 8/100
3500/3500 [==============================] - 0s 84us/sample - loss: 0.0424
Epoch 9/100
3500/3500 [==============================] - 0s 74us/sample - loss: 0.0422
Epoch 10/100
3500/3500 [==============================] - 0s 84us/sample - loss: 0.0419
Epoch 11/100
3500/3500 [==============================] - 0s 56us/sample - loss: 0.0417
Epoch 12/100


3500/3500 [==============================] - 0s 51us/sample - loss: 0.0016
Epoch 94/100
3500/3500 [==============================] - 0s 51us/sample - loss: 0.0016
Epoch 95/100
3500/3500 [==============================] - 0s 50us/sample - loss: 0.0015
Epoch 96/100
3500/3500 [==============================] - 0s 50us/sample - loss: 0.0014
Epoch 97/100
3500/3500 [==============================] - 0s 81us/sample - loss: 0.0013
Epoch 98/100
3500/3500 [==============================] - 0s 53us/sample - loss: 0.0012
Epoch 99/100
3500/3500 [==============================] - 0s 51us/sample - loss: 0.0012
Epoch 100/100
3500/3500 [==============================] - 0s 55us/sample - loss: 0.0011


In [9]:
#evaluate model

print("\n Model Evaluation \n")

model.evaluate(x_test, y_test, verbose=1)


 Model Evaluation 

1500/1500 [==============================] - 0s 207us/sample - loss: 9.9191e-04


0.0009919095279183239

In [10]:

#predict based on model

data = np.array([[0.1, 0.2], [0.2, 0.2]])
predictions = model.predict(data)


print("\n Some Predictions:")
for d, p in zip(data, predictions):
    print("{} + {} {}".format(d[0], d[1], p[0]))



 Some Predictions:
0.1 + 0.2 0.3160060942173004
0.2 + 0.2 0.4065200090408325
